### PR TITLE
remove contents.xcworkspacedata files and fix .gitignore

### PR DESCRIPTION
**Pull request by johnkdoe**
as recommended by the well used https://gist.github.com/adamgit/3786883

### CODE REVIEW

**Comment by goaway** [comment]
I'm good with this.

**Comment by kgoodier** [comment]
CI is broken. I'm not sure why it can't find the SPDY.xcodeproj/project.xcworkspace file for this pull request. I pulled the PR down locally and it builds fine. I'll look into this more later.

**Comment by johnkdoe** [comment]
any further word on this?  just saw that this was still here as i'm about to submit a pull request for updating the version-check from 6.1 to 6.3 … i looked at the details of the failure; nothing immediately occurs to me as to why this may be happening.

**Comment by kgoodier** [comment]
Fixed with commit https://github.com/kgoodier/CocoaSPDY/commit/17f96e10a92f76d9a82ea257e817a5cc622fd470, issued new PR https://github.com/twitter/CocoaSPDY/pull/112.

**Comment by johnkdoe** [comment]
uh … should i re-do the pull-request for the original changes having to do with the .gitignore file that this was for?

**Comment by kgoodier** [comment]
Your commit is in https://github.com/twitter/CocoaSPDY/pull/112 along with my extra one that should fix the build. Just waiting for Travis to verify the PR now. Seems to be stuck.

**Pull request closed without merging**
